"""Added the UserAuditMixins and more field and also change the name

Revision ID: 42777e92d4cf
Revises: e36bb66d1531
Create Date: 2024-11-18 07:38:06.483394

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42777e92d4cf"
down_revision: Union[str, None] = "e36bb66d1531"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("profile_image_url", sa.Unicode(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("phone_number", sa.Unicode(length=30), nullable=True)
    )
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("created_by", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("updated_by", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("deleted_by", sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, "users", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "users", "users", ["updated_by"], ["id"])
    op.create_foreign_key(None, "users", "users", ["deleted_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "deleted_by")
    op.drop_column("users", "updated_by")
    op.drop_column("users", "created_by")
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "profile_image_url")
    op.drop_column("users", "email_verified")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
