"""Adding the address model

Revision ID: 7b19fd27fd71
Revises: 42777e92d4cf
Create Date: 2024-11-18 09:20:35.296829

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b19fd27fd71"
down_revision: Union[str, None] = "42777e92d4cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("street_address", sa.Unicode(length=255), nullable=False),
        sa.Column("apartment", sa.Unicode(length=255), nullable=True),
        sa.Column("city", sa.Unicode(length=100), nullable=False),
        sa.Column("state", sa.Unicode(length=100), nullable=True),
        sa.Column("country", sa.Unicode(length=100), nullable=False),
        sa.Column("postal_code", sa.Unicode(length=20), nullable=True),
        sa.Column(
            "address_type",
            sa.Enum("SHIPPING", "BILLING", name="addresstype"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("deleted_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("address")
    # ### end Alembic commands ###
